from __future__ import annotations

import calendar
import json
import math
import re
import sqlite3
from datetime import date
from contextlib import closing
from pathlib import Path
from typing import Iterable

import pandas as pd
from sqlalchemy import inspect, text
from sqlalchemy.engine import Connection

from storage import StorageError, connect as _connect, local_db_path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DB_PATH = DATA_DIR / "expenses.db"
DEFAULT_WORKBOOK = DATA_DIR / "NTU Monthly budget.xlsx"

MAIN_FUND_LIMIT = 800.0
EMERGENCY_FUND_LIMIT = 200.0

DEFAULT_BUDGETS = {
    "Food": 570.0,
    "Personal": 100.0,
    "Transportation": 30.0,
    "Mobile and Services": 55.0,
    "Air Con": 45.0,
}

RESERVED_CATEGORIES = {"Emergency Fund"}
RESERVED_CATEGORY_KEYS = {category.casefold() for category in RESERVED_CATEGORIES}

ESSENTIAL_DEFAULTS = {
    "Food", "Transportation", "Mobile and Services", "Air Con"
}


def _is_reserved_category(category: object) -> bool:
    return str(category).strip().casefold() in RESERVED_CATEGORY_KEYS


def _execute(conn: Connection, statement: str, parameters=()):
    """Bind the existing SQL's positional parameters for either SQL dialect.

    Statements are developer-owned SQL; all user values remain bound parameters.
    These statements contain no question-mark literals or SQL operators.
    """
    pieces = statement.split("?")
    if len(pieces) != len(parameters) + 1:
        raise ValueError("SQL parameter count does not match")
    query = pieces[0] + "".join(f":p{i}" + part for i, part in enumerate(pieces[1:]))
    return conn.execute(text(query), {f"p{i}": value for i, value in enumerate(parameters)})


def _columns(conn: Connection, table: str) -> set[str]:
    return {column["name"] for column in inspect(conn).get_columns(table)}


def _read_frame(query: str, conn: Connection) -> pd.DataFrame:
    return pd.read_sql_query(text(query), conn)


def _month_key(d: date) -> str:
    return d.strftime("%Y-%m")


def _month_spend_total(conn: Connection, target_date: date) -> float:
    """Return spend for target month, including undated legacy seed rows only
    when target_date is in the current month.
    """
    month_key = _month_key(target_date)
    current_month_key = _month_key(date.today())
    if month_key == current_month_key:
        row = _execute(conn,
            """
            SELECT COALESCE(SUM(amount), 0)
            FROM expenses
            WHERE lower(trim(category)) != 'emergency fund'
              AND (
                    substr(expense_date, 1, 7) = ?
                    OR (expense_date IS NULL AND entry_mode = 'legacy')
                  )
            """,
            (month_key,),
        ).fetchone()
    else:
        row = _execute(conn,
            """
            SELECT COALESCE(SUM(amount), 0)
            FROM expenses
            WHERE lower(trim(category)) != 'emergency fund'
              AND substr(expense_date, 1, 7) = ?
            """,
            (month_key,),
        ).fetchone()
    return float(row[0] or 0.0)


def fund_status(total_spent: float) -> dict[str, float]:
    total_spent = max(float(total_spent or 0.0), 0.0)
    main_used = min(total_spent, MAIN_FUND_LIMIT)
    main_remaining = max(MAIN_FUND_LIMIT - total_spent, 0.0)
    emergency_required = max(total_spent - MAIN_FUND_LIMIT, 0.0)
    emergency_used = min(emergency_required, EMERGENCY_FUND_LIMIT)
    emergency_remaining = max(EMERGENCY_FUND_LIMIT - emergency_used, 0.0)
    over_total_funds = max(
        total_spent - MAIN_FUND_LIMIT - EMERGENCY_FUND_LIMIT, 0.0
    )
    return {
        "total_spent": total_spent,
        "main_used": main_used,
        "main_remaining": main_remaining,
        "main_utilization": (
            total_spent / MAIN_FUND_LIMIT * 100 if MAIN_FUND_LIMIT else 0.0
        ),
        "emergency_used": emergency_used,
        "emergency_remaining": emergency_remaining,
        "over_total_funds": over_total_funds,
        "total_available": MAIN_FUND_LIMIT + EMERGENCY_FUND_LIMIT,
    }


def init_db() -> None:
    with _connect(write=True) as conn:
        if inspect(conn).has_table("app_metadata"):
            version = _execute(
                conn, "SELECT value FROM app_metadata WHERE key = 'initialized'"
            ).scalar_one_or_none()
            if version == "1":
                return
        had_expenses = inspect(conn).has_table("expenses")
        had_budgets = inspect(conn).has_table("budgets")
        primary_key = (
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if conn.dialect.name == "postgresql"
            else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        schema = f"""
            CREATE TABLE IF NOT EXISTS expenses (
                id {primary_key},
                expense_date TEXT,
                amount DOUBLE PRECISION NOT NULL CHECK(amount >= 0),
                description TEXT NOT NULL DEFAULT '',
                category TEXT NOT NULL,
                payment_method TEXT NOT NULL DEFAULT '',
                is_essential INTEGER NOT NULL DEFAULT 0,
                source TEXT NOT NULL DEFAULT 'app',
                entry_mode TEXT NOT NULL DEFAULT 'individual',
                period_key TEXT,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS budgets (
                category TEXT PRIMARY KEY,
                monthly_budget DOUBLE PRECISION NOT NULL CHECK(monthly_budget >= 0)
            );

            CREATE TABLE IF NOT EXISTS emergency_uses (
                period_key TEXT PRIMARY KEY,
                expense_date TEXT NOT NULL,
                emergency_used_after DOUBLE PRECISION NOT NULL DEFAULT 0,
                reason TEXT NOT NULL,
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE IF NOT EXISTS app_metadata (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            );
            """
        for statement in schema.split(";"):
            if statement.strip():
                _execute(conn, statement)
        if conn.dialect.name == "postgresql":
            # The table-owning app role still has access. API roles (for example
            # Supabase's anon/authenticated roles) get no access without policies.
            for table in ("expenses", "budgets", "emergency_uses", "app_metadata"):
                _execute(conn, f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")

        cols = _columns(conn, "expenses")
        if "entry_mode" not in cols:
            _execute(conn,
                "ALTER TABLE expenses ADD COLUMN entry_mode TEXT NOT NULL DEFAULT 'individual'"
            )
        if "period_key" not in cols:
            _execute(conn, "ALTER TABLE expenses ADD COLUMN period_key TEXT")

        _execute(conn,
            """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_weekly_category_period
            ON expenses(period_key, category)
            WHERE entry_mode = 'weekly' AND period_key IS NOT NULL
            """
        )

        # Old versions treated Emergency Fund as a budget/expense category.
        # It is now a funding reserve, so remove any stale category rows.
        _execute(conn,
            "DELETE FROM expenses WHERE lower(trim(category)) = 'emergency fund'"
        )
        _execute(conn,
            "DELETE FROM budgets WHERE lower(trim(category)) = 'emergency fund'"
        )

        initialized = _execute(
            conn, "SELECT value FROM app_metadata WHERE key = 'initialized'"
        ).fetchone()
        if not initialized:
            if not had_budgets:
                _replace_budgets(conn, DEFAULT_BUDGETS)
            if not had_expenses:
                if conn.dialect.name == "postgresql" and local_db_path().exists():
                    _restore_snapshot(conn, _snapshot_from_sqlite(local_db_path()))
                elif DEFAULT_WORKBOOK.exists():
                    _import_workbook(conn, DEFAULT_WORKBOOK, replace=True)
            _execute(conn, "INSERT INTO app_metadata(key, value) VALUES ('initialized', '1')")


def count_expenses() -> int:
    with _connect() as conn:
        return int(
            _execute(conn,
                "SELECT COUNT(*) FROM expenses "
                "WHERE lower(trim(category)) != 'emergency fund'"
            ).fetchone()[0]
        )


def get_expenses() -> pd.DataFrame:
    with _connect() as conn:
        df = _read_frame(
            """
            SELECT id, expense_date, amount, description, category,
                   payment_method, is_essential, source, entry_mode,
                   period_key, created_at
            FROM expenses
            WHERE lower(trim(category)) != 'emergency fund'
            ORDER BY
              CASE WHEN expense_date IS NULL OR expense_date = '' THEN 1 ELSE 0 END,
              expense_date DESC,
              id DESC
            """,
            conn,
        )
    if df.empty:
        return pd.DataFrame(
            columns=[
                "id", "expense_date", "amount", "description", "category",
                "payment_method", "is_essential", "source", "entry_mode",
                "period_key", "created_at", "date",
            ]
        )
    df["date"] = pd.to_datetime(df["expense_date"], errors="coerce")
    df["is_essential"] = df["is_essential"].astype(bool)
    return df


def get_emergency_uses() -> pd.DataFrame:
    with _connect() as conn:
        return _read_frame(
            """
            SELECT period_key, expense_date, emergency_used_after, reason, updated_at
            FROM emergency_uses
            ORDER BY expense_date DESC, period_key DESC
            """,
            conn,
        )


def week_period_key(d: date) -> str:
    iso = d.isocalendar()
    return f"{iso.year}-W{iso.week:02d}"


def upsert_weekly_expenses(
    week_ending: date,
    amounts: dict[str, float],
    emergency_reason: str = "",
) -> dict:
    """Replace category totals for one ISO week.

    When the month's spending exceeds the S$800 main fund, the excess is
    considered Emergency Fund usage. A reason is required for that save.
    """
    period_key = week_period_key(week_ending)
    cleaned = {
        str(category).strip(): max(float(amount or 0), 0.0)
        for category, amount in amounts.items()
        if str(category).strip() and not _is_reserved_category(category)
    }

    with _connect(write=True) as conn:
        old_reason_row = _execute(conn,
            "SELECT reason FROM emergency_uses WHERE period_key = ?",
            (period_key,),
        ).fetchone()
        old_reason = str(old_reason_row._mapping["reason"]).strip() if old_reason_row else ""

        _execute(conn,
            "DELETE FROM expenses WHERE entry_mode = 'weekly' AND period_key = ?",
            (period_key,),
        )

        inserted = 0
        weekly_total = 0.0
        for category, amount in cleaned.items():
            if amount <= 0:
                continue
            _execute(conn,
                """
                INSERT INTO expenses
                (expense_date, amount, description, category, payment_method,
                 is_essential, source, entry_mode, period_key)
                VALUES (?, ?, ?, ?, '', ?, 'weekly', 'weekly', ?)
                """,
                (
                    week_ending.isoformat(),
                    amount,
                    f"Weekly total · {period_key}",
                    category,
                    int(category in ESSENTIAL_DEFAULTS),
                    period_key,
                ),
            )
            inserted += 1
            weekly_total += amount

        month_total = _month_spend_total(conn, week_ending)
        status = fund_status(month_total)

        if status["emergency_used"] > 0:
            reason = emergency_reason.strip() or old_reason
            if not reason:
                raise ValueError(
                    "A reason is required because this update uses the Emergency Fund."
                )
            _execute(conn,
                """
                INSERT INTO emergency_uses
                    (period_key, expense_date, emergency_used_after, reason, updated_at)
                VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
                ON CONFLICT(period_key) DO UPDATE SET
                    expense_date = excluded.expense_date,
                    emergency_used_after = excluded.emergency_used_after,
                    reason = excluded.reason,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (
                    period_key,
                    week_ending.isoformat(),
                    status["emergency_used"],
                    reason,
                ),
            )
        else:
            _execute(conn,
                "DELETE FROM emergency_uses WHERE period_key = ?",
                (period_key,),
            )
            # If the month is back below the main-fund ceiling after a correction,
            # no Emergency Fund explanation for that month should remain.
            _execute(conn,
                "DELETE FROM emergency_uses WHERE substr(expense_date, 1, 7) = ?",
                (_month_key(week_ending),),
            )

    return {
        "period_key": period_key,
        "categories_saved": inserted,
        "weekly_total": weekly_total,
        "month_total": month_total,
        **status,
    }


def get_weekly_totals() -> pd.DataFrame:
    with _connect() as conn:
        return _read_frame(
            """
            SELECT
                e.period_key,
                MAX(e.expense_date) AS week_ending,
                SUM(e.amount) AS total_spent,
                COUNT(*) AS categories_recorded,
                MAX(u.reason) AS emergency_reason
            FROM expenses e
            LEFT JOIN emergency_uses u ON u.period_key = e.period_key
            WHERE e.entry_mode = 'weekly'
              AND e.period_key IS NOT NULL
              AND lower(trim(e.category)) != 'emergency fund'
            GROUP BY e.period_key
            ORDER BY e.period_key DESC
            """,
            conn,
        )


def delete_week(period_key: str) -> None:
    with _connect(write=True) as conn:
        date_row = _execute(conn,
            """
            SELECT MAX(expense_date) AS expense_date
            FROM expenses
            WHERE entry_mode = 'weekly' AND period_key = ?
            """,
            (period_key,),
        ).fetchone()
        expense_date = date_row._mapping["expense_date"] if date_row else None

        _execute(conn,
            "DELETE FROM expenses WHERE entry_mode = 'weekly' AND period_key = ?",
            (period_key,),
        )
        _execute(conn,
            "DELETE FROM emergency_uses WHERE period_key = ?",
            (period_key,),
        )

        if expense_date:
            target_date = date.fromisoformat(str(expense_date)[:10])
            month_total = _month_spend_total(conn, target_date)
            if month_total <= MAIN_FUND_LIMIT:
                _execute(conn,
                    "DELETE FROM emergency_uses WHERE substr(expense_date, 1, 7) = ?",
                    (_month_key(target_date),),
                )


def delete_expenses(ids: Iterable[int]) -> None:
    ids = [int(x) for x in ids]
    if not ids:
        return
    placeholders = ",".join("?" for _ in ids)
    with _connect(write=True) as conn:
        _execute(conn, f"DELETE FROM expenses WHERE id IN ({placeholders})", ids)


def get_budgets() -> dict[str, float]:
    with _connect() as conn:
        rows = _execute(conn,
            """
            SELECT category, monthly_budget
            FROM budgets
            WHERE lower(trim(category)) != 'emergency fund'
            ORDER BY category
            """
        ).fetchall()
    return {str(r._mapping["category"]): float(r._mapping["monthly_budget"]) for r in rows}


def _replace_budgets(conn: Connection, budgets: dict[str, float]) -> None:
    _execute(conn, "DELETE FROM budgets")
    for category, amount in budgets.items():
        category = str(category).strip()
        if category and not _is_reserved_category(category):
            _execute(conn, "INSERT INTO budgets(category, monthly_budget) VALUES (?, ?)",
                     (category, max(float(amount), 0.0)))


def replace_budgets(budgets: dict[str, float]) -> None:
    with _connect(write=True) as conn:
        _replace_budgets(conn, budgets)


def upsert_budget(category: str, monthly_budget: float) -> None:
    category = category.strip()
    if _is_reserved_category(category):
        return

    with _connect(write=True) as conn:
        _execute(conn,
            """
            INSERT INTO budgets(category, monthly_budget)
            VALUES (?, ?)
            ON CONFLICT(category) DO UPDATE SET monthly_budget = excluded.monthly_budget
            """,
            (category, max(float(monthly_budget), 0.0)),
        )


def delete_budget(category: str) -> None:
    with _connect(write=True) as conn:
        _execute(conn, "DELETE FROM budgets WHERE category = ?", (category,))


def _import_workbook(conn: Connection, path, replace: bool = False) -> dict:
    """Import spendable expenses and category budgets from the workbook.

    Emergency Fund rows are skipped because the S$200 reserve is a funding
    source that is only drawn after the S$800 main fund is exhausted.
    """

    raw_tx = pd.read_excel(path, sheet_name="Transactions", header=None)
    rows = []
    reserved_rows_skipped = 0

    for _, row in raw_tx.iterrows():
        if len(row) < 5:
            continue
        amount = pd.to_numeric(row.iloc[2], errors="coerce")
        category = row.iloc[4]
        if pd.isna(amount) or pd.isna(category):
            continue
        category = str(category).strip()
        if not category or category.lower() == "category":
            continue
        if _is_reserved_category(category):
            reserved_rows_skipped += 1
            continue

        parsed_date = pd.to_datetime(row.iloc[1], errors="coerce")
        expense_date = None if pd.isna(parsed_date) else parsed_date.date()
        description = "" if pd.isna(row.iloc[3]) else str(row.iloc[3]).strip()
        rows.append((expense_date, float(abs(amount)), description, category))

    budgets: dict[str, float] = {}
    try:
        raw_summary = pd.read_excel(path, sheet_name="Summary", header=None)
        for _, row in raw_summary.iterrows():
            if len(row) < 4:
                continue
            category = row.iloc[1]
            budget = pd.to_numeric(row.iloc[3], errors="coerce")
            if pd.isna(category) or pd.isna(budget):
                continue
            category = str(category).strip()
            if category in DEFAULT_BUDGETS:
                budgets[category] = float(budget)
    except Exception:
        budgets = {}

    if replace:
        _execute(conn, "DELETE FROM expenses")
        _execute(conn, "DELETE FROM emergency_uses")
    else:
        _execute(conn,
            "DELETE FROM expenses WHERE lower(trim(category)) = 'emergency fund'"
        )

    for expense_date, amount, description, category in rows:
        _execute(conn,
            """
            INSERT INTO expenses
            (expense_date, amount, description, category, payment_method,
             is_essential, source, entry_mode, period_key)
            VALUES (?, ?, ?, ?, '', ?, 'excel', 'legacy', NULL)
            """,
            (
                expense_date.isoformat() if expense_date else None,
                amount,
                description,
                category,
                int(category in ESSENTIAL_DEFAULTS),
            ),
        )

    if budgets:
        _replace_budgets(conn, budgets)

    return {
        "expenses_imported": len(rows),
        "budget_categories_imported": len(budgets),
        "undated_expenses": sum(1 for r in rows if r[0] is None),
        "reserved_rows_skipped": reserved_rows_skipped,
    }


def import_workbook(path, replace: bool = False) -> dict:
    """Import a path or uploaded workbook without staging a shared local file."""
    with _connect(write=True) as conn:
        return _import_workbook(conn, path, replace=replace)


BACKUP_FIELDS = {
    "expenses": (
        "expense_date", "amount", "description", "category", "payment_method",
        "is_essential", "source", "entry_mode", "period_key", "created_at",
    ),
    "budgets": ("category", "monthly_budget"),
    "emergency_uses": (
        "period_key", "expense_date", "emergency_used_after", "reason", "updated_at",
    ),
}


def export_backup() -> bytes:
    """Export one consistent snapshot, including budgets and emergency reasons."""
    snapshot = {"format": "budget-tracker", "version": 1}
    with _connect() as conn:
        for table, fields in BACKUP_FIELDS.items():
            result = _execute(conn, f"SELECT {', '.join(fields)} FROM {table}")
            snapshot[table] = [dict(row) for row in result.mappings()]
    return json.dumps(snapshot, indent=2, allow_nan=False).encode("utf-8")


def _validate_snapshot(snapshot: dict) -> dict:
    if (not isinstance(snapshot, dict) or snapshot.get("format") != "budget-tracker"
            or snapshot.get("version") != 1):
        raise ValueError("Choose a Budget Tracker backup JSON file (version 1).")
    cleaned = {"format": "budget-tracker", "version": 1}
    for table, fields in BACKUP_FIELDS.items():
        rows = snapshot.get(table)
        if not isinstance(rows, list):
            raise ValueError(f"Backup is missing the {table} records.")
        cleaned[table] = []
        seen = set()
        for row in rows:
            if not isinstance(row, dict) or any(field not in row for field in fields):
                raise ValueError(f"An incomplete {table} record was found in the backup.")
            item = {field: row[field] for field in fields}
            if "category" in item:
                if not isinstance(item["category"], str) or not item["category"].strip():
                    raise ValueError("Backup categories must be non-empty text.")
                if _is_reserved_category(item["category"]):
                    continue
            numeric = {"amount", "monthly_budget", "emergency_used_after"}
            for field, value in item.items():
                if field in numeric:
                    if (isinstance(value, bool) or not isinstance(value, (int, float))
                            or not math.isfinite(value) or value < 0):
                        raise ValueError("Backup amounts must be finite, non-negative numbers.")
                elif field == "is_essential":
                    if value not in (0, 1):
                        raise ValueError("Invalid essential flag in backup.")
                    item[field] = int(value)
                elif field in {"expense_date", "period_key"} and value is None and table == "expenses":
                    continue
                elif not isinstance(value, str):
                    raise ValueError(f"Invalid {field} in backup.")
            if item.get("expense_date"):
                try:
                    date.fromisoformat(item["expense_date"])
                except ValueError:
                    raise ValueError("Backup dates must use YYYY-MM-DD.") from None
            if table == "expenses":
                if item["entry_mode"] not in {"individual", "weekly", "legacy"}:
                    raise ValueError("Invalid entry mode in backup.")
                if item["entry_mode"] == "weekly":
                    if (not item["expense_date"] or not item["period_key"]
                            or week_period_key(date.fromisoformat(item["expense_date"])) != item["period_key"]):
                        raise ValueError("A weekly backup record has an invalid date or week.")
                    key = (item["period_key"], item["category"])
                else:
                    key = None
            else:
                key = item["category"] if table == "budgets" else item["period_key"]
                if table == "emergency_uses" and (not key or not item["reason"].strip() or not item["expense_date"]):
                    raise ValueError("An emergency record is missing its week, date or reason.")
            if key is not None:
                if key in seen:
                    raise ValueError(f"Duplicate {table} records in backup.")
                seen.add(key)
            cleaned[table].append(item)
    return cleaned


def _restore_snapshot(conn: Connection, snapshot: dict) -> dict[str, int]:
    snapshot = _validate_snapshot(snapshot)
    for table, fields in BACKUP_FIELDS.items():
        _execute(conn, f"DELETE FROM {table}")
        for row in snapshot[table]:
            _execute(conn,
                     f"INSERT INTO {table} ({', '.join(fields)}) VALUES ({', '.join('?' for _ in fields)})",
                     tuple(row[field] for field in fields))
    return {table: len(snapshot[table]) for table in BACKUP_FIELDS}


def restore_backup(content: bytes, *, replace: bool = False) -> dict[str, int]:
    try:
        snapshot = json.loads(content)
    except (ValueError, UnicodeError):
        raise ValueError("Choose a valid Budget Tracker backup JSON file.") from None
    snapshot = _validate_snapshot(snapshot)
    with _connect(write=True) as conn:
        if not replace:
            populated = any(_execute(conn, f"SELECT COUNT(*) FROM {table}").scalar_one()
                            for table in ("expenses", "emergency_uses"))
            budgets = dict(_execute(conn, "SELECT category, monthly_budget FROM budgets").all())
            if populated or (budgets and budgets != DEFAULT_BUDGETS):
                raise ValueError("Data already exists. Confirm replacement to restore this backup.")
        return _restore_snapshot(conn, snapshot)


def _snapshot_from_sqlite(path: Path) -> dict:
    """Read an existing local database without changing or deleting the source."""
    snapshot = {"format": "budget-tracker", "version": 1}
    defaults = {"entry_mode": "individual", "period_key": None}
    try:
        with closing(sqlite3.connect(path.resolve().as_uri() + "?mode=ro", uri=True)) as conn:
            conn.row_factory = sqlite3.Row
            conn.execute("BEGIN")
            tables = {row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type = 'table'")}
            if not {"expenses", "budgets"}.issubset(tables):
                raise ValueError("Local database has an unsupported schema.")
            for table in BACKUP_FIELDS:
                snapshot[table] = (
                    [{**defaults, **dict(row)} for row in conn.execute(f"SELECT * FROM {table}")]
                    if table in tables else []
                )
        return _validate_snapshot(snapshot)
    except (sqlite3.Error, ValueError):
        raise StorageError(
            "The existing local database could not be migrated. It has been kept intact; "
            "export a backup from the local app and restore it after configuring cloud storage."
        ) from None


def current_cycle_expenses(
    df: pd.DataFrame,
    today: date | None = None,
) -> pd.DataFrame:
    """Current month plus undated legacy spreadsheet entries."""
    if df.empty:
        return df.copy()

    today = today or date.today()
    dated_current = (
        df["date"].notna()
        & (df["date"].dt.year == today.year)
        & (df["date"].dt.month == today.month)
    )
    undated_legacy = df["date"].isna() & (df["entry_mode"] == "legacy")
    return df[dated_current | undated_legacy].copy()


def week_label(row: pd.Series) -> str:
    period = row.get("period_key")
    if isinstance(period, str) and period:
        return period
    if pd.notna(row.get("date")):
        d = row["date"]
        iso = d.isocalendar()
        return f"{iso.year}-W{iso.week:02d}"

    text = str(row.get("description", ""))
    match = re.search(r"week\s*(\d+)", text, flags=re.I)
    if match:
        return f"Week {match.group(1)}"
    return "Legacy / undated"


def month_days(today: date | None = None) -> tuple[int, int, int]:
    today = today or date.today()
    days_total = calendar.monthrange(today.year, today.month)[1]
    elapsed = today.day
    remaining_including_today = days_total - today.day + 1
    return days_total, elapsed, remaining_including_today
